// Pokémon Extinction additions.
//
// Every Pokemon in Pokémon Extinction is predetermined: the trainers' teams come from trainers.party and the
// player's box mons from fixed pools. The only thing a player chooses is which box mons they got and
// what they hold. So in this calc:
//
//   - the left side lists only the player's imported box, the right side only trainer sets
//   - the "Pokémon Extinction Box" picker imports box mons straight from the ROM's pools
//   - loading a trainer applies its map weather and starting statuses to the field
//   - Trick Room and Swamp are taken into account for the faster/slower speed colours
//
// Data comes from backups/extinction.js, generated by the hack repo's tools/calc_export/export_calc.py.
(function () {
    var EXTINCTION_TITLE = "Pokémon Extinction";
    var OWNED_KEY = "extinctionOwnedBoxMons";

    function isExtinction() {
        return typeof TITLE === "string" && TITLE === EXTINCTION_TITLE;
    }

    function extinctionData() {
        return typeof backup_data === "object" && backup_data ? backup_data : {};
    }

    // ------------------------------------------------------------------------------------------
    // Set lists
    // ------------------------------------------------------------------------------------------

    window.extinctionSetOptionAllowed = function (option, side) {
        if (!isExtinction()) return true;
        if (!option.set) return false; // bare species rows would allow free-form sets
        if (side === "player") return !!option.isCustom;
        return !option.isCustom && option.set !== "Blank Set";
    };

    // ------------------------------------------------------------------------------------------
    // Speed order
    // ------------------------------------------------------------------------------------------

    function isGrounded(pokemon) {
        if ($("#gravity").prop("checked")) return true;
        if (pokemon.hasItem && pokemon.hasItem("Iron Ball")) return true;
        if (pokemon.hasType && pokemon.hasType("Flying")) return false;
        if (pokemon.hasAbility && pokemon.hasAbility("Levitate")) return false;
        if (pokemon.hasItem && pokemon.hasItem("Air Balloon")) return false;
        return true;
    }

    function affectedBySwamp(pokemon) {
        if (!pokemon) return true;
        if (pokemon.hasItem && pokemon.hasItem("Heavy-Duty Boots")) return false;
        if (pokemon.hasAbility && pokemon.hasAbility("Magic Guard")) return false;
        return isGrounded(pokemon);
    }

    // Called from performCalculations with the final Speed stats. Swamp is the Grass/Water Pledge
    // side effect: a quarter of the Speed for grounded mons without Boots or Magic Guard.
    window.extinctionAdjustSpeeds = function (spe1, spe2, p1, p2) {
        var out = { p1: spe1, p2: spe2, trickRoom: false };
        if (!isExtinction()) return out;
        if ($("#ext-swampL").prop("checked") && affectedBySwamp(p1)) out.p1 = Math.floor(spe1 / 4);
        if ($("#ext-swampR").prop("checked") && affectedBySwamp(p2)) out.p2 = Math.floor(spe2 / 4);
        out.trickRoom = $("#ext-trickroom").prop("checked");
        return out;
    };

    // ------------------------------------------------------------------------------------------
    // Field controls
    // ------------------------------------------------------------------------------------------

    function addFieldControls() {
        if ($("#ext-field").length) return;
        var html =
            '<div id="ext-field" class="btn-group" title="Pokémon Extinction field effects">' +
            '<input class="visually-hidden calc-trigger" type="checkbox" id="ext-trickroom" />' +
            '<label class="btn btn-small btn-left" for="ext-trickroom">Trick Room</label>' +
            '<input class="visually-hidden calc-trigger" type="checkbox" id="ext-swampL" />' +
            '<label class="btn btn-small btn-mid" for="ext-swampL" title="Swamp on your side: grounded Pokemon have 1/4 Speed">Swamp (you)</label>' +
            '<input class="visually-hidden calc-trigger" type="checkbox" id="ext-swampR" />' +
            '<label class="btn btn-small btn-right" for="ext-swampR" title="Swamp on the trainer\'s side">Swamp (foe)</label>' +
            '</div>' +
            '<div id="ext-field-notes" class="ext-field-notes"></div>';
        $("#gravity").parent().after(html);
        $("#ext-field input").on("change", function () {
            if (typeof performCalculations === "function") performCalculations();
        });
    }

    function checkTerrain(name) {
        $('input[name="terrain"]').prop("checked", false);
        if (name) $('input[name="terrain"][value="' + name + '"]').prop("checked", true);
    }

    function checkWeather(value) {
        var input = $('input[name="weather"][value="' + value + '"]');
        if (input.length) input.prop("checked", true);
    }

    // Starting Status names exactly as trainers.party spells them.
    var WEATHER_STATUSES = {
        "Sun": "Sun", "Rain": "Rain", "Sandstorm": "Sand", "Sand": "Sand", "Snow": "Snow", "Hail": "Hail",
        "Desolate Land": "Harsh Sunshine", "Primordial Sea": "Heavy Rain", "Delta Stream": "Strong Winds",
    };
    var TERRAIN_STATUSES = {
        "Electric Terrain": "Electric", "Grassy Terrain": "Grassy",
        "Misty Terrain": "Misty", "Psychic Terrain": "Psychic",
    };

    function applyTrainerField(info) {
        var notes = [];

        // Reset what a trainer can set, so nothing carries over from the previous one.
        checkTerrain(null);
        $("#clear").prop("checked", true);
        $("#gravity, #srL, #srR, #steelsurgeL, #steelsurgeR, #ext-trickroom, #ext-swampL, #ext-swampR").prop("checked", false);
        $("#spikesL0, #spikesR0").prop("checked", true);

        if (info.map_weather) {
            checkWeather(info.map_weather);
            notes.push("Map weather: " + info.map_weather);
        }
        if (info.map_terrain) {
            checkTerrain(info.map_terrain);
            notes.push("Map fog: " + info.map_terrain + " Terrain");
        }

        (info.starting_status || []).forEach(function (status) {
            var base = status.replace(/ Temporary$/, "");
            var spikes = base.match(/^(Toxic )?Spikes (Player|Opponent) L(\d)$/);
            var side = / Player$/.test(base) ? "L" : / Opponent$/.test(base) ? "R" : null;

            if (WEATHER_STATUSES[base]) {
                checkWeather(WEATHER_STATUSES[base]);
            } else if (TERRAIN_STATUSES[base]) {
                checkTerrain(TERRAIN_STATUSES[base]);
            } else if (base === "Trick Room") {
                $("#ext-trickroom").prop("checked", true);
            } else if (base === "Gravity") {
                $("#gravity").prop("checked", true);
            } else if (base === "Torment Weather") {
                $("#clear").prop("checked", true); // replaces any other weather; residual damage only
            } else if (/^Stealth Rock/.test(base) && side) {
                $("#sr" + side).prop("checked", true);
            } else if (/^Sharp Steel/.test(base) && side) {
                $("#steelsurge" + side).prop("checked", true);
            } else if (spikes && !spikes[1]) {
                $("#spikes" + (spikes[2] === "Player" ? "L" : "R") + spikes[3]).prop("checked", true);
            } else if (/^Swamp/.test(base) && side) {
                $("#ext-swamp" + side).prop("checked", true);
            }
            notes.push(status);
        });

        $("#ext-field-notes").text(notes.length ? notes.join(" · ") : "");
    }

    var lastTrainerId = null;

    function onOpposingSetChange() {
        if (!isExtinction()) return;
        var fullSetName = $(this).val() || "";
        var pokemonName = fullSetName.substring(0, fullSetName.indexOf(" ("));
        var setName = fullSetName.substring(fullSetName.indexOf("(") + 1, fullSetName.lastIndexOf(")"));
        var set = setdex && setdex[pokemonName] ? setdex[pokemonName][setName] : null;
        var info = set && extinctionData().trainer_info ? extinctionData().trainer_info[set.tr_id] : null;
        if (!info || set.tr_id === lastTrainerId) return; // keep manual field changes within one fight
        lastTrainerId = set.tr_id;
        // After the core handler, which resets the field and picks singles/doubles.
        setTimeout(function () {
            applyTrainerField(info);
            if (typeof performCalculations === "function") performCalculations();
        }, 50);
    }

    // ------------------------------------------------------------------------------------------
    // Mega / Primal toggle
    //
    // A trainer's Mega holds its stone and evolves on its first turn, so both forms matter: the base
    // form takes the hit on the turn it comes in, the Mega does everything after. The Form dropdown
    // can already switch between them; this is the one-click version of it, and it shows up only
    // when the held item actually changes the form.
    // ------------------------------------------------------------------------------------------

    // The ability list holds the abilities the calc knows; a hack-only one is added so it at least
    // shows, even though the damage engine has no behaviour for it.
    function setAbility(panel, ability) {
        if (!ability) return;
        var select = panel.find(".ability");
        if (!select.find('option[value="' + ability + '"]').length) {
            select.append($("<option>").attr("value", ability).text(ability));
        }
        select.val(ability).change();
    }

    // Upstream only refreshes the left sprite when the form changes.
    window.updateRightPokeSprite = function (speciesName) {
        var name = (typeof getSpriteSpeciesName === "function" ? getSpriteSpeciesName(speciesName) : speciesName)
            .toLowerCase().replace(" ", "").replace(".", "").replace("\u2019", "").replace(":", "-").replace(/-s$/, "");
        if (name.indexOf("galarian-") === 0) name = name.slice("galarian-".length) + "-galar";
        if (name.indexOf("hisuian-") === 0) name = name.slice("hisuian-".length) + "-hisui";
        if (name.indexOf("alolan-") === 0) name = name.slice("alolan-".length) + "-alola";
        var style = typeof trainerSprites !== "undefined" ? trainerSprites : "front";
        var ext = typeof suffix !== "undefined" && suffix ? suffix : "png";
        $("#p2 .poke-sprite").attr("src", "./img/" + style + "/" + name.replace("-glitched", "") + "." + ext);
    };

    function formTarget(item, formeSelect) {
        if (!item) return null;
        var stones = (typeof calc !== "undefined" && calc.MEGA_STONES) || {};
        var candidates = [];
        if (stones[item]) {
            // Older entries map a stone to the base species, newer ones straight to the Mega.
            // Charizardite X / Mewtwonite Y and friends pick one of two Megas, named by the suffix.
            var suffix = (item.match(/ (X|Y)$/) || [])[1];
            candidates.push(stones[item]);
            if (suffix) candidates.push(stones[item] + "-Mega-" + suffix);
            candidates.push(stones[item] + "-Mega");
        }
        if (item === "Red Orb") candidates.push("Groudon-Primal");
        if (item === "Blue Orb") candidates.push("Kyogre-Primal");
        for (var i = 0; i < candidates.length; i++) {
            if (/-(Mega|Primal)/.test(candidates[i]) && formeSelect.find('option[value="' + candidates[i] + '"]').length) {
                return candidates[i];
            }
        }
        return null;
    }

    // The Form dropdown is built from the calc's own data, so it offers forms this ROM does not
    // have (Sevii forms, Megas the hack never added) and both Mega Charizards whatever stone is
    // held. A Pokemon can only reach the form its item gives it, so drop the rest.
    function filterFormeOptions(panel, target) {
        var formeSelect = $(panel).find(".forme");
        var poks = extinctionData().poks || {};
        var current = formeSelect.val();
        formeSelect.find("option").each(function () {
            var name = $(this).attr("value");
            if (name === current) return;
            var unreachableForm = /-(Mega|Primal)/.test(name) && name !== target;
            if (!poks[name] || unreachableForm) $(this).remove();
        });
        // Nothing left to choose between: the calc hides a single-option dropdown anyway.
        formeSelect.closest("div").toggleClass("hide", formeSelect.find("option").length < 2 && !target);
    }

    function updateFormToggle(panel) {
        var formeSelect = $(panel).find(".forme");
        var item = $(panel).find(".item").val();
        var button = $(panel).find(".ext-form-toggle");
        var current = formeSelect.val() || "";
        // Switching to a Mega clears the stone in the calc, so once a Mega or Primal form is
        // selected the current form is what tells us where to switch back to.
        var target = /-(Mega|Primal)/.test(current) ? current : formTarget(item, formeSelect);

        if (!isExtinction()) {
            button.remove();
            return;
        }
        if (!target) {
            filterFormeOptions(panel, null);
            button.remove();
            return;
        }
        if (!button.length) {
            button = $('<button type="button" class="bs-btn ext-form-toggle"></button>');
            formeSelect.closest("div").removeClass("hide").append(button);
            button.on("click", function () {
                var to = $(this).attr("data-to");
                var stone = $(this).attr("data-item");
                var back = $(this).attr("data-ability");
                $(panel).find(".forme").val(to).change();
                // Mega Evolving clears the stone in the calc; put it back on the way down.
                if (stone && !$(panel).find(".item").val()) {
                    $(panel).find(".item").val(stone).change();
                }
                // The forme change re-applies the SET's ability, which belongs to the base form.
                // A Mega has its own (Mega Ampharos is Fluffy in this hack, not Static).
                var wanted = /-(Mega|Primal)/.test(to)
                    ? (window.pokedex && pokedex[to] && pokedex[to].abilities && pokedex[to].abilities[0])
                    : back;
                setAbility($(panel), wanted);
            });
        }
        filterFormeOptions(panel, target);
        var isBase = current !== target;
        var label = /-Primal/.test(target) ? "Primal" : "Mega";
        if (isBase && item) button.attr("data-item", item); // remember the stone for the way back
        if (isBase) button.attr("data-ability", $(panel).find(".ability").val() || "");
        button.text(isBase ? "\u2192 " + label : "\u2192 Base")
              .attr("data-to", isBase ? target : target.replace(/-(Mega.*|Primal)$/, ""));
    }

    function updateFormToggles() {
        preferBoxSetName();
        updateFormToggle("#p1");
        updateFormToggle("#p2");
        updateBoxTag();
    }

    // ------------------------------------------------------------------------------------------
    // Box picker
    // ------------------------------------------------------------------------------------------

    function getOwned() {
        try {
            return JSON.parse(localStorage.getItem(OWNED_KEY) || "[]");
        } catch (e) {
            return [];
        }
    }

    function setOwned(list) {
        try {
            localStorage.setItem(OWNED_KEY, JSON.stringify(list));
        } catch (e) { /* private window: the picker still works for this visit */ }
    }

    var STAT_LABELS = [["hp", "HP"], ["at", "Atk"], ["df", "Def"], ["sa", "SpA"], ["sd", "SpD"], ["sp", "Spe"]];

    function showdownText(species, set) {
        var lines = [species + (set.item ? " @ " + set.item : "")];
        lines.push("Level: " + set.level);
        lines.push(set.nature + " Nature");
        if (set.ability) lines.push("Ability: " + set.ability);
        lines.push("IVs: " + STAT_LABELS.map(function (s) { return set.ivs[s[0]] + " " + s[1]; }).join(" / "));
        set.moves.forEach(function (m) { lines.push("- " + m); });
        return lines.join("\n");
    }

    function spriteSrc(species) {
        var name = typeof getPreviewSpriteName === "function" ? getPreviewSpriteName(species) : species.toLowerCase();
        var style = typeof sprite_style !== "undefined" ? sprite_style : "newhd";
        return "./img/" + style + "/" + name + ".png";
    }

    function poolGroups() {
        var groups = {};
        var sets = extinctionData().player_sets || {};
        Object.keys(sets).sort().forEach(function (species) {
            Object.keys(sets[species]).forEach(function (label) {
                var pool = label.replace(/ #\d+$/, "");
                (groups[pool] = groups[pool] || []).push({ species: species, label: label, set: sets[species][label] });
            });
        });
        return groups;
    }

    function boxOf(pool) {
        var m = pool.match(/^Box (\d+)/);
        return m ? m[1] : pool;
    }

    function renderPicker() {
        var owned = getOwned();
        var groups = poolGroups();
        var boxes = {};
        Object.keys(groups).sort().forEach(function (pool) {
            (boxes[boxOf(pool)] = boxes[boxOf(pool)] || []).push(pool);
        });
        var html = "";
        Object.keys(boxes).sort().forEach(function (box) {
            html += '<div class="ext-box" data-box="' + box + '"><h3>Box ' + box +
                ' <button type="button" class="bs-btn ext-box-import" data-box="' + box + '">Import Box ' + box +
                '</button></h3>';
            boxes[box].forEach(function (pool) {
                var sub = pool.replace(/^Box \d+\s*/, "");
                html += '<h4>' + (sub || "Pool") + '</h4><div class="ext-pool">';
                groups[pool].forEach(function (entry) {
                    var key = entry.species + "|" + entry.label;
                    var set = entry.set;
                    var tip = entry.species + " Lv" + set.level + " (" + set.nature + ", " + set.ability + ")" +
                        (set.item ? " @ " + set.item : "") + "\n" + set.moves.join(", ");
                    html += '<div class="ext-mon' + (owned.indexOf(key) !== -1 ? " owned" : "") + '" data-key="' +
                        key.replace(/"/g, "&quot;") + '" title="' + tip.replace(/"/g, "&quot;") + '">' +
                        '<img src="' + spriteSrc(entry.species) + '" loading="lazy" alt="">' +
                        '<span>' + entry.species + '</span></div>';
                });
                html += "</div>";
            });
            html += "</div>";
        });
        $("#ext-box-list").html(html);
        $("#ext-box-count").text(owned.length + " selected");
    }

    var LABELS_KEY = "extinctionBoxLabels";

    function getBoxLabels() {
        try {
            return JSON.parse(localStorage.getItem(LABELS_KEY) || "{}");
        } catch (e) {
            return {};
        }
    }

    // The calc stores every imported mon under one set name, "My Box", so the list would read
    // "Charizard (My Box)" whichever box it came from.
    //
    // Rather than rewrite the label - the species and set name are parsed back out of it in around
    // thirty places - the box name is registered as a second name for the same set object, and the
    // "My Box" entry is hidden from the lists. "Charizard (Box 5 Starter)" is then a real set that
    // every one of those places can still look up. Only setdex gets the extra name; the stored box
    // in localStorage stays keyed by "My Box", which the box view and fragsheet rely on.
    var aliasedSets = [];

    function syncBoxSetNames() {
        if (typeof setdex !== "object" || !setdex) return;
        aliasedSets.forEach(function (entry) {
            if (setdex[entry[0]]) delete setdex[entry[0]][entry[1]];
        });
        aliasedSets = [];
        Object.keys(setdex).forEach(function (species) {
            var boxSet = setdex[species] && setdex[species]["My Box"];
            var label = boxSet && boxLabelFor(species);
            if (!label || label === "My Box" || setdex[species][label]) return;
            setdex[species][label] = boxSet;
            aliasedSets.push([species, label]);
        });
    }

    function decorateBoxOptions(options) {
        syncBoxSetNames();
        return options.filter(function (option) {
            // Hide the raw "My Box" row when the same set is listed under its box name.
            return !(option && option.set === "My Box" && boxLabelFor(option.pokemon));
        });
    }

    function boxLabelFor(speciesName) {
        var labels = getBoxLabels();
        if (labels[speciesName]) return labels[speciesName];
        // Megas the calc derives from a box mon (Abomasnow-Mega) inherit the base mon's box.
        var base = String(speciesName || "").replace(/-(Mega.*|Primal)$/, "");
        return labels[base] || "";
    }

    // Clicking a box icon selects the set by its stored name, so the label would read "(My Box)"
    // again. Both names point at the same set, so the label can be swapped without re-applying it.
    function preferBoxSetName() {
        var selector = $("#p1 .set-selector").first();
        var value = selector.val() || "";
        var match = value.match(/^(.*) \(My Box\)$/);
        var label = match && boxLabelFor(match[1]);
        if (!label) return;
        var renamed = match[1] + " (" + label + ")";
        if (typeof setdex === "object" && setdex[match[1]] && setdex[match[1]][label]) {
            selector.val(renamed);
            $("#p1 .select2-chosen").first().text(renamed);
        }
    }

    // A tag next to the Pokemon list also names the box, for the panel itself.
    function updateBoxTag() {
        var chosen = $("#p1 .set-selector").first().val() || $("#p1 .select2-chosen").first().text() || "";
        var species = chosen.split(" (")[0].trim();
        var isBoxSet = /\(([^)]*)\)\s*$/.test(chosen) && !!boxLabelFor(species);
        var label = isBoxSet ? boxLabelFor($("#p1 .forme").val() || species) : "";
        var tag = $("#ext-box-tag");
        if (!tag.length) {
            tag = $('<div id="ext-box-tag" class="ext-box-tag"></div>');
            $("#p1 .set-selector").first().closest("div").after(tag);
        }
        tag.text(label).toggle(!!label);
    }

    function importOwned() {
        var sets = extinctionData().player_sets || {};
        // The calc keeps one box set per species. When two pools share a species, import the later
        // box last so its set is the one kept - that is the version a player has later in the game.
        var keys = getOwned().slice().sort(function (a, b) {
            var la = a.slice(a.indexOf("|") + 1), lb = b.slice(b.indexOf("|") + 1);
            return la < lb ? -1 : la > lb ? 1 : 0;
        });
        var texts = keys.map(function (key) {
            var sep = key.indexOf("|");
            var species = key.slice(0, sep);
            var set = sets[species] && sets[species][key.slice(sep + 1)];
            return set ? showdownText(species, set) : null;
        }).filter(Boolean);

        // Replace the box rather than merging: a new split wipes the player's old encounters.
        // updateDex compares against the STORED box to know what to remove, so the stored box must
        // still be the old one when it runs - it then stores the result itself. Only "My Box" sets
        // are touched; the trainer sets live in the same table and stay.
        if (typeof updateDex === "function" && typeof getStoredCustomSets === "function" &&
            typeof removeMyBoxEntries === "function") {
            updateDex(removeMyBoxEntries(getStoredCustomSets()));
            customSets = getStoredCustomSets();
        }
        // The party and the left-side selection point at the old box.
        $("#clear-party").click();
        try {
            if (/\(My Box\)$/.test(localStorage.left || "")) localStorage.removeItem("left");
        } catch (e) { /* storage unavailable */ }

        var labels = {};
        keys.forEach(function (key) {
            var sep = key.indexOf("|");
            labels[key.slice(0, sep)] = key.slice(sep + 1).replace(/ #\d+$/, "");
        });
        try {
            localStorage.setItem(LABELS_KEY, JSON.stringify(labels));
        } catch (e) { /* storage unavailable */ }

        if (texts.length && typeof addSets === "function") {
            addSets(texts.join("\n\n"), "My Box");
            syncBoxSetNames();
            // Show a Pokemon from the new box instead of one that no longer exists.
            $(".player-poks .trainer-pok, .player-megas .trainer-pok").first().click();
        } else if (typeof get_box === "function") {
            get_box();
        }
    }

    function addBoxPicker() {
        if ($("#ext-box-open").length) return;
        $("#read-save").hide();
        $(".import-team-text").attr("placeholder", "Use \"Pokémon Extinction Box\" to pick the box Pokemon you received.");
        $("#read-save").after('<button type="button" class="bs-btn bs-btn-default" id="ext-box-open">Pokémon Extinction Box</button>');
        $("body").append(
            '<div id="ext-box-modal" class="ext-modal" hidden>' +
            '<div class="ext-modal-dialog" role="dialog" aria-label="Pokémon Extinction box">' +
            '<div class="ext-modal-head"><strong>Which box Pokemon did you get?</strong>' +
            '<span id="ext-box-count"></span>' +
            '<button type="button" class="bs-btn" id="ext-box-none">Unselect all</button>' +
            '<button type="button" class="bs-btn" id="ext-box-import">Import selected</button>' +
            '<button type="button" class="bs-btn" id="ext-box-close">Close</button></div>' +
            '<p class="ext-modal-help">"Import Box N" imports that whole box. Or click single Pokemon and use "Import selected". ' +
            'Every import replaces the previously imported Pokemon; importing nothing empties the box. Hover for a set; held items can be changed on the left after importing.</p>' +
            '<div id="ext-box-list"></div></div></div>'
        );

        $("#ext-box-open").on("click", function () {
            renderPicker();
            $("#ext-box-modal").prop("hidden", false);
        });
        $("#ext-box-close").on("click", function () {
            $("#ext-box-modal").prop("hidden", true);
        });
        $("#ext-box-import").on("click", function () {
            importOwned();
            $("#ext-box-modal").prop("hidden", true);
        });
        // A new split hands out a new box and wipes the old one, so importing a box replaces
        // whatever was imported before.
        $("#ext-box-none").on("click", function () {
            setOwned([]);
            renderPicker();
        });
        $("#ext-box-list").on("click", ".ext-box-import", function () {
            var box = $(this).attr("data-box");
            setOwned($('#ext-box-list .ext-box[data-box="' + box + '"] .ext-mon').map(function () {
                return $(this).attr("data-key");
            }).get());
            importOwned();
            $("#ext-box-modal").prop("hidden", true);
        });
        $("#ext-box-list").on("click", ".ext-mon", function () {
            var key = $(this).attr("data-key");
            var owned = getOwned();
            var at = owned.indexOf(key);
            if (at === -1) owned.push(key); else owned.splice(at, 1);
            setOwned(owned);
            $(this).toggleClass("owned", at === -1);
            $("#ext-box-count").text(owned.length + " selected");
        });
    }

    // ------------------------------------------------------------------------------------------

    $(document).on("change", ".opposing.set-selector", onOpposingSetChange);
    $(document).on("change", ".set-selector, .item, .forme", function () {
        setTimeout(updateFormToggles, 60); // after the panel is rebuilt
    });

    $(function () {
        // backup_data loads asynchronously; wait for it before building the Extinction-only UI.
        var tries = 0;
        var timer = setInterval(function () {
            tries++;
            if (isExtinction() && extinctionData().player_sets) {
                clearInterval(timer);
                addFieldControls();
                addBoxPicker();
                updateFormToggles();
                if (typeof getSetOptions === "function" && !getSetOptions.extinctionWrapped) {
                    var original = getSetOptions;
                    window.getSetOptions = function (sets) {
                        var options = original(sets);
                        return isExtinction() ? decorateBoxOptions(options) : options;
                    };
                    window.getSetOptions.extinctionWrapped = true;
                }
            } else if (tries > 200) {
                clearInterval(timer);
            }
        }, 50);
    });
})();
